Test failure for jms-sqs (#378)
* Test failure for jms-sqs

Failure https://ge.micronaut.io/s/fshrmjxbbaeee

````
Bean definition [io.micronaut.jms.configuration.JMSConnectionFactoryBeanProcessor] could not be loaded: Error processing bean definition [Definition: io.micronaut.jms.sqs.configuration.SqsConfiguration]: Failed to inject value for parameter [builder] of method [sqsJmsConnectionFactory] of class: io.micronaut.jms.sqs.configuration.SqsConfiguration

Message: No bean of type [software.amazon.awssdk.services.sqs.SqsClientBuilder] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
Path Taken: SqsConfiguration.sqsJmsConnectionFactory(SqsConfigurationProperties config,SqsClientBuilder builder) --> SqsConfiguration.sqsJmsConnectionFactory(SqsConfigurationProperties config,[SqsClientBuilder builder])
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [io.micronaut.jms.configuration.JMSConnectionFactoryBeanProcessor] could not be loaded: Error processing bean definition [Definition: io.micronaut.jms.sqs.configuration.SqsConfiguration]: Failed to inject value for parameter [builder] of method [sqsJmsConnectionFactory] of class: io.micronaut.jms.sqs.configuration.SqsConfiguration

Message: No bean of type [software.amazon.awssdk.services.sqs.SqsClientBuilder] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
Path Taken: SqsConfiguration.sqsJmsConnectionFactory(SqsConfigurationProperties config,SqsClientBuilder builder) --> SqsConfiguration.sqsJmsConnectionFactory(SqsConfigurationProperties config,[SqsClientBuilder builder])
	at app//io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1979)
	at app//io.micronaut.cont
```

* Fix AWS version

---------

Co-authored-by: Tim Yates <tim.yates@gmail.com>